name: flutter_opencc_ffi_web
description: Web platform implementation of flutter_opencc_ffi
repository: https://github.com/dolphinxx/flutter_opencc_ffi/tree/master/flutter_opencc_ffi_web
issue_tracker: https://github.com/dolphinxx/flutter_opencc_ffi/issues
version: 0.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: flutter_opencc_ffi
    platforms:
      web:
        pluginClass: FlutterOpenccFfiPlugin
        fileName: flutter_opencc_ffi_web.dart
#  assets:
#    - assets/opencc/

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_opencc_ffi_platform_interface: ^0.0.3
#  flutter_opencc_ffi_platform_interface:
#    path: ../flutter_opencc_ffi_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter